-- Criar tabelas
CREATE TABLE TB_CLIENTES
(
    CPF VARCHAR2(11),
    NOME VARCHAR2 (100),
    ENDERECO1 VARCHAR2 (150),
    ENDERECO2 VARCHAR2(150),
    BAIRRO VARCHAR2 (50),
    CIDADE VARCHAR2 (50),
    ESTADO VARCHAR2(2),
    CEP VARCHAR2 (8),
    DATA_NASCIMENTO DATE,
    IDADE INTEGER,
    SEXO VARCHAR2 (1),
    LIMITE_CREDITO NUMBER(15,2),
    VOLUME_COMPRA NUMBER,
    PRIMEIRA_COMPRA NUMBER(1)
)

CREATE TABLE TB_VENDEDORES
(
    MATRICULA VARCHAR2(5),
    NOME VARCHAR2(100),
    DATA_ADMISSAO DATE,
    PERCENTUAL_COMISSAO NUMBER
);

CREATE TABLE TB_PRODUTOS
(
    PRODUTO VARCHAR2(20),
    NOME VARCHAR2(150),
    EMBALAGEM VARCHAR2(50),
    TAMANHO VARCHAR2(50),
    SABOR VARCHAR2(50),
    PRECO_LISTA NUMBER
)
--- fim do topico

-- Inserir valores nas tabelas
INSERT INTO TB_PRODUTOS
(PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA)
VALUES
('1', 'Carioca', 'Pacote', '1kg', 'Feijão puro', 1);

INSERT INTO TB_VENDEDORES
(MATRICULA, NOME, DATA_ADMISSAO, PERCENTUAL_COMISSAO)
VALUES
('00233', 'João Geraldo da Fonseca', '01/12/2015', 0.10);
--- fim do topico

-- Alterar dados da tabela
UPDATE TB_PRODUTOS SET EMBALAGEM = 'Lata'
WHERE PRODUTO = 1;

UPDATE TB_PRODUTOS SET 
    NOME = 'Carioquinha', 
    EMBALAGEM = 'Saco'
WHERE PRODUTO = 1;

SELECT * FROM TB_PRODUTOS;
--- fim do topico

-- Deletar registros de uma tabela
DELETE FROM TB_PRODUTOS
WHERE PRODUTO = 2;

SELECT * FROM TB_PRODUTOS;
--- fim do topico

/*
    Alteramdo uma tabela
    E
    Incluindo uma PK na tabela
*/
ALTER TABLE TB_PRODUTOS 
ADD CONSTRAINT PK_TB_PRODUTOS PRIMARY KEY (PRODUTO);

ALTER TABLE TB_CLIENTES
ADD CONSTRAINT PK_TB_CLIENTES PRIMARY KEY (CPF);

SELECT * FROM TB_CLIENTES;
--- fim do topico
