-- Criando tabelas
CREATE TABLE PRODUTOS
(
CODIGO VARCHAR(10) NOT NULL,
DESCRITOR VARCHAR(10) NULL,
SABOR VARCHAR(50) NULL,
TAMANHO VARCHAR(50) NULL,
EMBALAGEM VARCHAR (50) NULL,
PRECO_LISTA FLOAT NULL,
PRIMARY KEY (CODIGO)
);

CREATE TABLE VENDEDORES
(
MATRICULA VARCHAR(5) NOT NULL,
NOME VARCHAR(100) NULL,
BAIRRO VARCHAR(50),
COMISSAO FLOAT NULL,
DATA_ADMISSAO DATE NULL,
FERIAS INTEGER NULL,
PRIMARY KEY (MATRICULA)
);
--- fim do topico

-- Alterando tabelas
ALTER TABLE VENDEDORES
RENAME COLUMN DATA_ADMISSAUMO TO DATA_ADMISSAO;
--- fim do topico

-- Criando tabelas com chaves estrangeiras
CREATE TABLE TABELA_DE_VENDAS
(
      NUMERO VARCHAR(5) NOT NULL
    , DATA_VENDA DATE NULL
    , CPF VARCHAR(11) NOT NULL
    , MATRICULA VARCHAR(5) NOT NULL
    , IMPOSTO FLOAT NULL
    , PRIMARY KEY (NUMERO)
);

ALTER TABLE TABELA_DE_VENDAS
ADD CONSTRAINT FK_CLIENTES
FOREIGN KEY (CPF) REFERENCES CLIENTES (CPF);


ALTER TABLE TABELA_DE_VENDAS
ADD CONSTRAINT FK_VENDEDORES
FOREIGN KEY (MATRICULA) REFERENCES VENDEDORES (MATRICULA);
--- fim do topico

-- Alterando o nome da tabela
ALTER TABLE TABELA_DE_VENDAS
RENAME TO NOTAS;
--- fim do topico

/*
Só criando o resto das tabelas
*/

CREATE TABLE ITENS_NOTAS
(
      NUMERO VARCHAR(5) NOT NULL
    , CODIGO VARCHAR(10) NOT NULL
    , QUANTIDADE INTEGER NULL
    , PRECO FLOAT
    , PRIMARY KEY (NUMERO, CODIGO)
);

ALTER TABLE ITENS_NOTAS
ADD CONSTRAINT FK_NOTAS
FOREIGN KEY (NUMERO) 
REFERENCES NOTAS (NUMERO);

ALTER TABLE ITENS_NOTAS
ADD CONSTRAINT FK_PRODUTOS
FOREIGN KEY (CODIGO) 
REFERENCES PRODUTOS (CODIGO);
--- fim do topico

-- Inserir dados na tabela
INSERT INTO PRODUTOS
(CODIGO, DESCRITOR, SABOR, TAMANHO, EMBALAGEM, PRECO_LISTA)
VALUES
('1040107', 'Light - 350 ml - Melancia', 'Melancia', '350 ml', 'Lata', 4.6);
--- fim do topico

-- Inserir dados na tabela a partir de outra tabela
INSERT INTO PRODUTOS
SELECT CODIGO_DO_PRODUTO AS CODIGO
, NOME_DO_PRODUTO AS DESCRITOR
, SABOR
, TAMANHO
, EMBALAGEM
, PRECO_DE_LISTA AS PRECO_LISTA
FROM TABELA_DE_PRODUTOS_FONTE
WHERE CODIGO_DO_PRODUTO <> '1040107';
--- fim do topico

-- Deletando linhas de forma dinâmica
DELETE FROM PRODUTOS P 
WHERE P.CODIGO IN
(
SELECT P.CODIGO
FROM PRODUTOS P
LEFT JOIN TABELA_DE_PRODUTOS_FONTE TPF ON P.CODIGO = TPF.CODIGO_DO_PRODUTO
WHERE TPF.CODIGO_DO_PRODUTO IS NULL
);
--- fim do topico

-- Duplicando uma tabela
CREATE TABLE PRODUTOS2 AS (SELECT * FROM PRODUTOS);
SELECT * FROM PRODUTOS2;
--- fim do topico

-- COMMIT e ROLLBACK
COMMIT;
ROLLBACK;
--- fim do topico

-- Trigger
/*CREATE OR REPLACE TRIGGER TG_TAB_FATURAMENTO
AFTER INSERT ON ITENS_NOTAS
BEGIN
-------------- coloque aqui sua lógica
END;*/
--- fim do topico