-- Criando tabelas
CREATE TABLE PRODUTOS
(
CODIGO VARCHAR(10) NOT NULL,
DESCRITOR VARCHAR(10) NULL,
SABOR VARCHAR(50) NULL,
TAMANHO VARCHAR(50) NULL,
EMBALAGEM VARCHAR (50) NULL,
PRECO_LISTA FLOAT NULL,
PRIMARY KEY (CODIGO)
);

CREATE TABLE VENDEDORES
(
MATRICULA VARCHAR(5) NOT NULL,
NOME VARCHAR(100) NULL,
BAIRRO VARCHAR(50),
COMISSAO FLOAT NULL,
DATA_ADMISSAO DATE NULL,
FERIAS INTEGER NULL,
PRIMARY KEY (MATRICULA)
);
--- fim do topico

-- Alterando tabelas
ALTER TABLE VENDEDORES
RENAME COLUMN DATA_ADMISSAUMO TO DATA_ADMISSAO;
--- fim do topico

-- Criando tabelas com chaves estrangeiras
CREATE TABLE TABELA_DE_VENDAS
(
      NUMERO VARCHAR(5) NOT NULL
    , DATA_VENDA DATE NULL
    , CPF VARCHAR(11) NOT NULL
    , MATRICULA VARCHAR(5) NOT NULL
    , IMPOSTO FLOAT NULL
    , PRIMARY KEY (NUMERO)
);

ALTER TABLE TABELA_DE_VENDAS
ADD CONSTRAINT FK_CLIENTES
FOREIGN KEY (CPF) REFERENCES CLIENTES (CPF);


ALTER TABLE TABELA_DE_VENDAS
ADD CONSTRAINT FK_VENDEDORES
FOREIGN KEY (MATRICULA) REFERENCES VENDEDORES (MATRICULA);
--- fim do topico

-- Alterando o nome da tabela
ALTER TABLE TABELA_DE_VENDAS
RENAME TO NOTAS;
--- fim do topico

/*
Só criando o resto das tabelas
*/

CREATE TABLE ITENS_NOTAS
(
      NUMERO VARCHAR(5) NOT NULL
    , CODIGO VARCHAR(10) NOT NULL
    , QUANTIDADE INTEGER NULL
    , PRECO FLOAT
    , PRIMARY KEY (NUMERO, CODIGO)
);

ALTER TABLE ITENS_NOTAS
ADD CONSTRAINT FK_NOTAS
FOREIGN KEY (NUMERO) 
REFERENCES NOTAS (NUMERO);

ALTER TABLE ITENS_NOTAS
ADD CONSTRAINT FK_PRODUTOS
FOREIGN KEY (CODIGO) 
REFERENCES PRODUTOS (CODIGO);
--- fim do topico

