-- Usando Alias
/*
    Duas formas de utilizar:
    1- Colocando "AS"
        Exemplo: "SELECT CPF AS IDENTIFICADOR FROM TABELA_DE_CLIENTES;"
    2- NÃO Colocando "AS"
        Exemplo: "SELECT CPF IDENTIFICADOR FROM TABELA_DE_CLIENTES;"
*/
--- fim do topico

-- Usando IN
SELECT *
FROM TABELA_DE_CLIENTES
WHERE CIDADE IN ('Rio de Janeiro', 'São Paulo')
    AND (IDADE BETWEEN 20 AND 25);
    
SELECT *
FROM TABELA_DE_CLIENTES
WHERE BAIRRO IN
(
    SELECT DISTINCT BAIRRO
    FROM TABELA_DE_VENDEDORES
);
--- fim do topico

-- Usando LIKE
SELECT *
FROM TABELA_DE_PRODUTOS
WHERE SABOR LIKE '%Limao%';
--- fim do topico

-- Usando DISTINCT
SELECT DISTINCT 
EMBALAGEM
FROM TABELA_DE_PRODUTOS;
--- fim do topico

-- Usando ROWNUM
SELECT TP.*
FROM TABELA_DE_PRODUTOS TP
WHERE ROWNUM <= 5;
--- fim do topico

-- Usando ORDER BY
SELECT *
FROM TABELA_DE_PRODUTOS
ORDER BY PRECO_DE_LISTA DESC;
--- fim do topico

-- Usando GROUP BY
/*
Só dá para agrupar se for:
    - somar (SUM)
    - saber valor máximo (MAX)
    - saber valor mínimo (MIN)
    - tirar média (AVG)
    - contar (COUNT)
*/
SELECT EMBALAGEM, MAX(PRECO_DE_LISTA)
FROM TABELA_DE_PRODUTOS
GROUP BY EMBALAGEM;
--- fim do topico

-- Usando HAVING
/*
    Serve para filtrar o 
    resultado do GROUP BY
*/
SELECT ESTADO, SUM(LIMITE_DE_CREDITO)
FROM TABELA_DE_CLIENTES
GROUP BY ESTADO
HAVING SUM(LIMITE_DE_CREDITO) >= 90000;
--- fim do topico

-- Usando CASE WHEN --> THEN --> ELSE --> END
/*
    IF, ELSE IF, ELSE, RETURN do SQL
*/
SELECT NOME_DO_PRODUTO, PRECO_DE_LISTA,
(CASE WHEN PRECO_DE_LISTA >= 12 THEN 'PRODUTO CARO'
      WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'PRODUTO EM CONTA'
      ELSE 'PRODUTO BARATO'
      END) AS CLASSIFICACAO
FROM TABELA_DE_PRODUTOS
ORDER BY CLASSIFICACAO;
--- fim do topico

-- Usando HAVING sem usar o HAVING
/*
Usando o HAVING primeiramente
*/
SELECT 
      EMBALAGEM
    , SUM(PRECO_DE_LISTA) AS SOMA_PRECO
FROM TABELA_DE_PRODUTOS
GROUP BY EMBALAGEM
HAVING SUM(PRECO_DE_LISTA) >= 80;

/*
Não usando o HAVING
*/
SELECT
      SUM_EMB.EMBALAGEM
    , SUM_EMB.SOMA_PRECO
FROM
(
SELECT 
      EMBALAGEM
    , SUM(PRECO_DE_LISTA) AS SOMA_PRECO
FROM TABELA_DE_PRODUTOS
GROUP BY EMBALAGEM
) SUM_EMB
WHERE SUM_EMB.SOMA_PRECO >= 80;
--- fim do topico

-- Criando e usando VIEW
/*
VIEW é um SELECT que se 
comporta como uma tabela
*/
CREATE VIEW VW_SUM_EMB AS 
SELECT 
      EMBALAGEM
    , SUM(PRECO_DE_LISTA) AS SOMA_PRECO
FROM TABELA_DE_PRODUTOS
GROUP BY EMBALAGEM;

/*
Fazendo SELECT com a VIEW criada
*/
SELECT
      EMBALAGEM
    , SOMA_PRECO
FROM VW_SUM_EMB
WHERE SOMA_PRECO > 80;

/*
Fazendo JOINs com a VIEW
*/
SELECT *
FROM TABELA_DE_PRODUTOS TP
INNER JOIN VW_SUM_EMB VW ON VW.EMBALAGEM = TP.EMBALAGEM
WHERE VW.SOMA_PRECO >= 80;
--- fim do topico

-- Funções no Oracle Database
...
--- fim do topico



